### ISSUE TITLE
nDCG not giving 1 for new SparkRankingMetrics(truth,truth)

### ISSUE THREAD

**Issue by thelabdude** [jongwook/spark-ranking-metrics#2]
just to validate I had everything setup correctly, I tried this:

val metrics = new SparkRankingMetrics(truthRatings, truthRatings)
metrics.ndcgAt(20)

should I expect 1 for the result since I'm comparing truth to truth?

I tried the same with Spark's built-in RankingMetrics class and it does return 1

**Comment by jongwook** [comment]
Thanks for the report; i could reproduce the issue. Will update shortly.

**Comment by jongwook** [comment]
I found an implementation bug where `NDCG@k` was calculated as 0 when the number of relevant items and the predicted items are both less than `k`; it is now fixed with b90881d.

I've made a breaking API change so that `SparkRankingMetrics` is now immutable, expecting column names as constructor parameters, and expects a `Dataset` which is a superclass of `DataFrame` as of Spark 2.0. I believe this change won't be too disruptive in your implementation.

I'll postpone the next tagging/maven central upload until I hear back from [Rival developers](https://github.com/recommenders/rival/commit/3eaa41e3fdda730d97549ffe4ac25467a9b9d433#commitcomment-22873747), where I found another issue that MAP can be less than 1.0 even for a perfect prediction. 

In the meantime, this is really a single-file project and I guess it will be easy to include the latest `SparkRankingMetrics.scala` file to your project.
